### ISSUE TITLE
Cannot find the example data used in the MIBITOF_breast_cancer.ipynb

### ISSUE THREAD

**Issue by huanlity** [theislab/graphcompass#42]
Hi, very exciting work! I really want to test it out on our own data. First, I want to make sure I can reproduce the results in the tutorial notebook. However I could not locate the breast cancer .h5ad file from https://data.mendeley.com/datasets/d87vg86zd8/3. I downloaded the whole thing but still could not find the example data file. Please advise. Thank you so much and good luck with the paper review!

Huan Wang
Broad Institute

**Comment by merelkuijs** [comment]
Hi Huan, thanks for reaching out! We built the .h5ad file from the .csv file present in that repo. We can probably upload the processing notebook here. I'll let you know when that's online.

**Comment by merelkuijs** [comment]
Hi Huan, please find the processing notebook in the `notebooks/processing` folder. There we show how to build the adata from the raw files you can download from the Mendeley repo. I hope that helps. 

Let me know if you have any further questions.

**Comment by huanlity** [comment]
Thanks a lot!

Huan
