### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Isiiiiii** [theislab/graphcompass#51]
Hello,

I'm excited to try the methods of your package, unfortunately I'm facing problems with the installation. I'm working on Mac with python 3.10. in a conda environment. Apparently there is a problem with the 'pygeos' package, but I can't get behind it. I would be very thankful for any advice on how to solve this. 

<img width="1172" alt="Errorcode_1" src="https://github.com/theislab/graphcompass/assets/86830782/757eac6d-600f-4364-b244-2fac9134b05a">
<img width="1155" alt="Errorcode_2" src="https://github.com/theislab/graphcompass/assets/86830782/44230264-763b-4945-8931-91a9bbf9916e">

**Comment by mayarali** [comment]
Hi @Isiiiiii, can you please tell me which version of `graphcompass` are you trying to install?

**Comment by merelkuijs** [comment]
When creating new environments, you can tell `conda` explicitly which version of Python to use:
`conda create -n myenv python=3.10` 

Could you try that and then install `graphcompass` once you have activated your environment?

**Comment by Isiiiiii** [comment]
Thank you for the answer. I tried that before with python 3.9 and 3.10 and it didn't work. Now I made it work by deactivating the base environment and created a new one with python 3.10 then. I installed version 0.1.1. of graphcompass.

**Comment by mayarali** [comment]
Glad to hear it's now working. I would recommend installing the latest version of graphcompass though `0.2.0`, where we added extra features and some datasets.

I will close this issue, but feel free to open a new one if you have further questions.

**Comment by mayarali** [comment]
I will close this issue, but feel free to open a new one if you have further questions.
