### ISSUE TITLE
error in np.array()

### ISSUE THREAD

**Issue by Bo-UT** [theislab/graphcompass#57]
Hi, 

Thanks for the nice package!
I ran into `ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (28,) + inhomogeneous part.` My python version is 3.10.13.  Thank you. 

<img width="655" alt="Screenshot 2024-05-20 at 6 14 17 AM" src="https://github.com/theislab/graphcompass/assets/55055062/ecdf014b-d6f9-4e58-9ea8-88b3364e583a">
<img width="825" alt="Screenshot 2024-05-20 at 6 14 45 AM" src="https://github.com/theislab/graphcompass/assets/55055062/90c279cb-8372-40df-82d7-bc9a3ef17cf4">

**Comment by mayarali** [comment]
@Bo-UT,

Could you please provide a screenshot showing the dimensions of your adata, in your case `wt`?

**Comment by Bo-UT** [comment]
Thank you! Here is the screen shot. 

<img width="778" alt="Screenshot 2024-05-26 at 7 35 58 AM" src="https://github.com/theislab/graphcompass/assets/55055062/405ba891-00e0-432e-8515-3eeec2f69e21">

**Comment by mayarali** [comment]
@Bo-UT Thanks for sharing the screenshot!
What is your `cluster_key` and `library_key`? And can you please specify how many samples (i.e. `library_key`) you have?

**Comment by mayarali** [comment]
@Bo-UT we will close this issue due to inactivity. Please feel free to open a new issue if you need further help.

**Comment by mayarali** [comment]
@Bo-UT we will close this issue due to inactivity. Please feel free to open a new issue if you need further help.
